# Generated by Django 2.2.6 on 2019-10-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191011_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_to_read',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
